#!/bin/bash
# nb: the swp file that editscript relies on is provided by nano
export TERM
red="$(tput setaf 9)"
bold="$(tput bold)"
boldred="$(tput setaf 9 bold)"
tput0="$(tput sgr0)"

editscript(){
  local scriptpath script path swp; scriptpath=$(realpath "$0" 2>/dev/null); script="${scriptpath##*/}"; path="${scriptpath%/*}"; swp="$path/.$script.swp"
     [[ ! -e "$swp" ]] && printf "\n\n%s\n\n" "$swp" && (/usr/bin/nano "$scriptpath") && exit
     printf "\n%s is already being edited.\n%s exists; try fg or look in another window.\n" "$scriptpath" "$swp"; exit ;}

pause(){ read -rp "$*" < /dev/tty; }

yn(){
  local yn
  while true; do
    printf '%s (y/n) ' "$1"
    read yn </dev/tty
      case $yn in
        [yY] ) return 0 ;;  # Success (true)
        [nN] ) return 1 ;;  # Failure (false)
           * ) echo "Please answer y or n." ;;
      esac
  done
}

[[ "$1" == @(edit|e|-e) ]] && editscript

if ! command -v mediainfo &> /dev/null; then
  mi=false
  if ! command -v ffprobe &> /dev/null; then
    echo "mediainfo and ffprobe could not be found. Please install one to continue."
    exit 1
  fi
else
    mi=true
fi

# check for flacs first
printf 'Current directory is %s\nChecking for flacs and permissions...\n' "$(pwd)"
flacs=(*flac)
[[ "$flacs" = '*flac' ]] && { printf '\n[%sERROR%s] %sNo flacs in the present working directory!%s\nPlease check and try again.\n(exit 1)\n' "$boldred" "$tput0" "$bold" "$tput0"; exit 1; }

# check if pwd is sshfs mount
findmnt -T . | grep -q "fuse.sshfs" && unset SUDO && fuse=true

if "${fuse:=false}"; then
  touchout="$(touch boobs 2>&1)"; fusetouch="$?"
  ! (( fusetouch )) && rm boobs
fi

# check for directory permissions
[[ (( fusetouch )) || "$fuse" != true && ! -w "$PWD" ]] &&
  if yn "$(printf '\nThe pwd %s is not writable.\nWould you like to "own" this directory?' "$(pwd)")"; then
    ownout=( "$(own 2>&1|tee /dev/tty; ec="$?")" )
    if (( ec )); then
      printf '\n[%sERROR%s] own returned an error:\n'  "$boldred" "$tput0"
      printf '%s\n' "${ownout[@]}"
      printf '\nFix permissions!\n(exit 1)\n\n'
      exit 1
    else
      printf %s\\n "${ownout[@]}"
    fi
  else
    printf '\n[%sERROR%s] Fix permissions!\n(exit 1)\n\n' "$boldred" "$tput0"
    exit 1
  fi

# check for write permission of flacs
for i in "${flacs[@]}"; do
  [[ ! -w "$i" ]] &&
    if yn "$(printf '\nThe file %s is not writable.\nWould you like to "own" this directory?' "$i")"; then
      ownout=( "$(own 2>&1; ec="$?")" )
      if ((ec)); then
        printf '\n[%sERROR%s] own returned an error:\n'  "$boldred" "$tput0"
        printf '%s\n' "${ownout[@]}"
        printf '\nFix permissions!\n(exit 1)\n'
        exit 1
      else
        printf %s\\n "${ownout[@]}"
      fi
    else
      printf '\n[%sERROR%s] Fix permissions!\n(exit 1)\n'  "$boldred" "$tput0"
      exit 1
    fi
done


#  if [[ "$fuse" != true && ! -w "$i" || ! -w "$PWD" ]] && yn "$(printf '\nDirectory or files are not writable.\nWould you like to "own" this directory?')"; then
#    own #|| printf '\nown returned an error.\nFix permissions!\n' && exit 1
#  else
#    printf \\nFix\ permissions\!\\n && exit 1
#  fi

for i in *flac; do
  if "$mi"; then
    bits=$(mediainfo --Output='Audio;%BitDepth%' "$i")
    Hz=$(mediainfo --Output='Audio;%SamplingRate%' "$i")
 else
    bits=$(ffprobe -v error -select_streams a:0 -show_entries stream=bits_per_raw_sample -of default=noprint_wrappers=1:nokey=1 "$i")
    Hz=$(ffprobe -v error -select_streams a:0 -show_entries stream=sample_rate -of default=noprint_wrappers=1:nokey=1 "$i")
  fi

#  if (( bits <= 16 )) || (( Hz < 48000 )); then
  if (( bits <= 16 )) || (( Hz < 44100 )); then
  # over=true
  # (( Hz == 48000 )) && yn "File is $bits/$Hz, continue with processing?" && over=false
  # if "$over"; then
      kHz=$(( Hz / 1000 ))
      kHzr=$(( Hz % 1000 ))
      kHzr="${kHzr%%0*}"
      [[ "$kHzr" ]] && kHz="$kHz.$kHzr"
      printf '%s%sThe file, %s%s%s%s, %s%sdoes not appear to be above 16/48 bits/kHz:%s\n Bit rate   : %s bits\n Sample rate: %s kHz\n%s%sPlease investigate. (exit 1)\n\n%s' \
       "$bold" \
       "$red" \
       "$tput0" \
       "$bold" \
       "$i" \
       "$tput0" \
       "$bold" \
       "$red" \
       "$tput0" \
       "$bits" \
       "$kHz" \
       "$bold" \
       "$red" \
       "$tput0"
      exit 1
  # fi
  fi

  if (( Hz != 48000 )) && (( Hz != 41000 )); then
    printf 'The sample rate is %s Hz.\n' "$Hz"
    if (( Hz > 48000 )) && ! "${changerate:=false}" ; then
      if yn "Do you want to set the sample rate to 48000 Hz?"; then
        Hz=48000
        changerate=true
      else
        printf 'Please investigate. (exit 1)'
        exit 1
      fi
    elif (( Hz > 48000 )) && "${changerate:=false}"; then
      Hz=48000
    fi
  fi

  if [[ "$i" = *".24."* ]]
    then
      flac24="$i"
      flac16="${flac24/.24.flac/.flac}"
      ffmpeg -hide_banner -nostdin -i "$flac24" -af aresample=osf=s16:dither_method=triangular_hp -n -ar "$Hz" "$flac16"
  else
    flac16="$i"
    flac24="${i/.flac/.24.flac}"
    mv "$i" "$flac24"
    ffmpeg -hide_banner -nostdin -i "$flac24" -af aresample=osf=s16:dither_method=triangular_hp -n -ar "$Hz" "$flac16"
  fi
done

mkdir "24-bit"
mv *.24.flac "24-bit"
rmr 24-bit </dev/tty
