#!/bin/bash

scriptname="$(realpath $0)"

function editscript(){
if [[ "$1" == "edit" ]]; then
 (/usr/bin/nano "$scriptname")
 exit
fi
}

function pause(){
   read -p "$*"
}

editscript "$1"

duration=$(find -type f -name "*.opus" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d:%02d:%02d\n",$t/3600,$t/60%60,$t%60' | tail -n 1)
hours=$(find -type f -name "*.opus" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d\n",$t/3600' | tail -n 1)
minutes=$(find -type f -name "*.opus" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d\n",$t/60%60' | tail -n 1)
seconds=$(find -type f -name "*.opus" -print0 | xargs -0 mplayer -vo dummy -ao dummy -identify 2>/dev/null | perl -nle '/ID_LENGTH=([0-9\.]+)/ && ($t +=$1) && printf "%02d\n",$t%60' | tail -n 1)
if [[ "$seconds" -gt 29 ]]; then ((minutes++)); fi
#printf "Duration $hours:$minutes hh:mm\n"
#printf "hours $hours\n"
#printf "minutes $minutes\n"
#printf "seconds $seconds\n"

#printf "Duration of ${PWD##*/}: %02d:%02d hh:mm\n" ${hours#0} ${minutes#0}
printf "%02d:%02d hh:mm ${PWD##*/} \n" "${hours#0}" "${minutes#0}"
